config/routes.rb
PixelflowBlog::Application.routes.draw do
  resources :blog_posts

  get 'login', to: 'sessions#login'
  get 'portfolio', to: 'portfolio#index'
  get 'laboratory', to: 'laboratory#index'
  get 'cv', to: 'cv#index'

  root to: 'portfolio#index'
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
	acts_as_url :title

	validates :title, :presence => true
	validates :body,  :presence => true

	def to_param
		url
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def authenticated
	if session[:logged_in].blank?
		flash[:notice] = 'Not authorized'
		respond_to do |format|
			format.html { redirect_to root_url }
			format.json { render json: {error: 'Not authorized'}, status: :unauthorized }
		end
	end
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_filter :authenticated, except: [:index, :show]

  respond_to :html, :xml, :json

  def index
    @blog_posts = BlogPost.order("blog_posts.created_at DESC").paginate(:per_page => 5, :page => params[:page])

	respond_with @blog_posts
  end


  def show
    @blog_post = BlogPost.where(url: params[:id]).first

	respond_with @blog_post
  end


  def new
    @blog_post = BlogPost.new

	respond_with @blog_post
  end


  def edit
    @blog_post = BlogPost.where(url: params[:id]).first
  end


  def create
    @blog_post = BlogPost.where(url: params[:id]).first

	if @blog_post.save
		flash[:notice] = 'Blog post was successfully created.'
	end

	respond_with @blog_post
  end


  def update
    @blog_post = BlogPost.where(url: params[:id]).first

    if @blog_post.update_attributes(params[:blog_post])
		flash[:notice] = 'Blog post was successfully updated.'
	end

	respond_with @blog_post
  end


  def destroy
    @blog_post = BlogPost.where(url: params[:id]).first
    @blog_post.destroy

	respond_with @blog_post
  end
end

app/controllers/laboratory_controller.rb
class LaboratoryController < ApplicationController
  def index
    @labs = [
      {name: 'Wobblygog' , url: 'http://codepen.io/zeroeth/full/gpXRex/ ', image: 'spinner.png'},
      {name: 'Palette Pie' , url: 'http://codepen.io/zeroeth/full/qKlBI/' , image: 'pie.png'},
      {name: 'Mon a moire' , url: 'http://codepen.io/zeroeth/full/baHzj/', image: 'shader.png'},
    ]
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
    @projects = [
      {name: 'Pixeltastic' , url: 'https://github.com/zeroeth/pixeltastic', image: 'goggles.png'},
      {name: 'Ebauche' , url: 'https://github.com/zeroeth/ebauche', image: 'clock.png'},
      {name: 'Square Blox' , url: 'https://github.com/zeroeth/squareblox', image: 'block.png'},
      {name: 'Gravity Escape' , url: 'https://github.com/zeroeth/Gravity-Escape', image: 'spacecrash.png'},
      {name: 'Brain.json' , url: 'https://github.com/zeroeth/brain.json', image: 'brain.png'},
      {name: 'Gratuitous Raytracing' , url: 'https://github.com/zeroeth/gratuitous_raytracing', image: 'sphere.png'},
      {name: 'dae.rb' , url: 'https://github.com/zeroeth/daerb', image: 'magic.png'},
      {name: 'Maze Dungeon' , url: 'https://github.com/zeroeth/maze_dungeon', image: 'maze.png'},
      {name: 'Shiver me Dithers' , url: 'https://github.com/zeroeth/shiver_me_dithers', image: 'dither.png'}
    ]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def login
		if Rails.application.config.passphrase.blank?
			flash[:notice] = 'Passphrase not configured'
			respond_to do |format|
				format.html { redirect_to root_url }
				format.json { render json: {error: 'Not Configured'}, status: :forbidden }
			end
		elsif params[:passphrase] == Rails.application.config.passphrase
			session[:logged_in] = true
			flash[:notice] = 'Welcome aboard'
			respond_to do |format|
				format.html { redirect_to root_url }
				format.json { head :ok }
			end
		else
			flash[:notice] = 'Not authorized'
			respond_to do |format|
				format.html { redirect_to root_url }
				format.json { render json: {error: 'Not authorized'}, status: :unauthorized }
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_disqus.html.haml
#disqus_thread
:javascript
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = 'pixelflow'; // required: replace example with your forum shortname

  // The following are highly recommended additional parameters. Remove the slashes in front to use.
  var disqus_identifier = "/#{Rails.env}/blog_post/#{@blog_post.id}";
  var disqus_title = "#{@blog_post.title}";
  // var disqus_url = 'http://example.com/permalink-to-page.html';

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
%noscript
  Please enable JavaScript to view the
  %a{:href => "http://disqus.com/?ref_noscript"} comments powered by Disqus.
%a.dsq-brlink{:href => "http://disqus.com"}
  blog comments powered by
  %span.logo-disqus Disqus

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<div class="blog_post petal petal_<%= @blog_post.id % 5 + 1 %>">
	<h1>Editing Blog Post</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @blog_post %> |
	<%= link_to 'Back', blog_posts_path %>
</div>

app/views/blog_posts/index.html.haml
- @blog_posts.each do |blog_post|
  .blog_post
    %h1.title
      =link_to blog_post.title, blog_post
    .blog_body
      = Maruku.new(blog_post.body).to_html.html_safe
.blog_pagination
  = will_paginate @blog_posts, class: 'digg_pagination'

app/views/blog_posts/new.html.erb
<div class="blog_post petal">
	<h1>New Blog Post</h1>

	<%= render 'form' %>

	<%= link_to 'Back', blog_posts_path %>
</div>

app/views/blog_posts/show.html.haml
.blog_post
  %h1.title
    = link_to @blog_post.title, @blog_post
  .blog_body
    = Maruku.new(@blog_post.body).to_html.html_safe

app/views/laboratory/index.html.haml
- @labs.each_with_index do |lab|
  .grid_12.alpha.omega
    .project{style: "background-image: url('#{image_path(lab[:image])}')"}
      %h1.title
        = link_to lab[:url], target: "_blank" do
          = lab[:name]

app/views/layouts/_about.html.haml
.personal_links
  %p
    Hi! My name is Kevin Alford and here you will find my ramblings on code, electronic music, robotics, and just about anything inbetween.
  %ul
    %li
      %strong= link_to 'Resume', "/Kevin Alford - resume.pdf"
    %li
      %strong= link_to 'Github', "http://github.com/zeroeth"
    %li
      %strong= link_to 'Twitter', "http://twitter.com/kevinalford"

app/views/layouts/_analytics.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-6510227-4']);
  _gaq.push(['_setDomainName', '.pixelflow.org']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/layouts/_fork_me.html.erb
<a href="http://github.com/zeroeth">
  <img style="position: absolute; top: 0; right: 0; border: 0;" src="/images/fork_me_red.png" alt="Fork me on GitHub">
</a>

app/views/layouts/_header.html.haml
.blog_header
  .center.logo
    = render 'layouts/hex_vector'
  .left.title
    %h1 Pixelflow
    .text
      An Intergalactic Discourse
  .right.social
    = link_to laboratory_path do
      <span class="icon icon-flask blueit"></span><span class="text blueit"><span class="d1">L</span><span class="d2">a</span><span class="d3">b</span><span class="d4">o</span><span class="d5">r</span><span class="d6">a</span><span class="d7">t</span><span class="d8">o</span><span class="d9">r</span><span class="d10">y</span></span>
  .right.social
    = link_to blog_posts_path do
      <span class="icon icon-bulb yellowit"></span><span class="text yellowit"><span class="d1">A</span><span class="d2">r</span><span class="d3">t</span><span class="d4">i</span><span class="d5">c</span><span class="d6">l</span><span class="d7">e</span><span class="d8">s</span></span>
  .right.social
    = link_to portfolio_path do
      <span class="icon icon-ruby pinkit"></span><span class="text pinkit"><span class="d1">P</span><span class="d2">r</span><span class="d3">o</span><span class="d4">j</span><span class="d5">e</span><span class="d6">c</span><span class="d7">t</span><span class="d8">s</span>
      </span>
  .clear

app/views/layouts/_hex_vector.html.erb
<svg id="svg3809" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://www.w3.org/2000/svg" height="600pt" width="600pt" version="1.1" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" viewBox="0 0 600 600">
 <metadata id="metadata3829">
  <rdf:RDF>
   <cc:Work rdf:about="">
    <dc:format>image/svg+xml</dc:format>
    <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"/>
    <dc:title/>
   </cc:Work>
  </rdf:RDF>
 </metadata>
 <path id="petal0" d="m186.79,300,56.602,98.039,113.21,0,56.602-98.039-56.602-98.039-113.21,0z" style="stroke-linejoin:miter;stroke:#f9f9f9;stroke-linecap:butt;stroke-miterlimit:4;stroke-width:6;fill:none;"/>
 <path id="petal4" d="m186.79,496.08,56.602,98.039,113.21,0,56.602-98.039-56.602-98.043-113.21,0z" style="stroke-linejoin:miter;stroke:#f9f9f9;stroke-linecap:butt;stroke-miterlimit:4;stroke-width:6;fill:none;"/>
 <path id="petal5" d="m73.586,300-56.606,98.039,56.606,98.043,113.21-0.00007,56.602-98.043-56.602-98.039z" style="stroke-linejoin:miter;stroke:#f9f9f9;stroke-linecap:butt;stroke-miterlimit:4;stroke-width:6;fill:none;"/>
 <path id="petal6" d="m186.79,103.92-113.21-0.00007-56.606,98.043,56.606,98.039,113.21,0.00005,56.602-98.039z" style="stroke-linejoin:miter;stroke:#f9f9f9;stroke-linecap:butt;stroke-miterlimit:4;stroke-width:6;fill:none;"/>
 <path id="petal1" d="m413.21,103.92-56.602-98.039-113.21,0-56.602,98.039,56.602,98.043,113.21,0z" style="stroke-linejoin:miter;stroke:#f9f9f9;stroke-linecap:butt;stroke-miterlimit:4;stroke-width:6;fill:none;"/>
 <path id="petal2" d="m526.41,300,56.606-98.039-56.606-98.043-113.21,0.00007-56.602,98.043,56.602,98.039z" style="stroke-linejoin:miter;stroke:#f9f9f9;stroke-linecap:butt;stroke-miterlimit:4;stroke-width:6;fill:none;"/>
 <path id="petal3" d="m413.21,496.08,113.21,0.00007,56.606-98.043-56.606-98.039-113.21-0.00005-56.602,98.039z" style="stroke-linejoin:miter;stroke:#f9f9f9;stroke-linecap:butt;stroke-miterlimit:4;stroke-width:6;fill:none;"/>
</svg>

app/views/layouts/_links.html.haml
.personal_links
  %h3 Places to visit
  %ul
    %li
      %strong= link_to 'Rails Guides',  "http://guides.rubyonrails.org"
    %li
      %strong= link_to 'Ruby5 Podcast', "http://ruby5.envylabs.com"
    %li
      %strong= link_to 'Synthtopia',    "http://www.synthtopia.com"
    %li
      %strong= link_to 'Adafruit',      "http://www.adafruit.com/blog"
    %li
      %strong= link_to 'Make: blog',    "http://blog.makezine.com"

app/views/layouts/_twitter.html.erb
<div class="tweet_box">
	<a class="twitter-timeline" height="400" href="https://twitter.com/kevinalford" data-widget-id="425019457388285952" data-chrome="noscrollbar noheader nofooter transparent">Tweets by @kevinalford</a>
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>

app/views/layouts/application.html.haml
!!! 5
%html{:xmlns => "http://www.w3.org/1999/xhtml", :lang => "en", "xml:lang" => "en"}
  %head
    %meta{:charset => "UTF-8"}
    %meta{:property => "og:image", :content => "#{request.protocol}#{request.host_with_port}#{image_path('hexflower_big.png')}"}
    %meta{:property => "og:type", :content => "blog"}
    %title PIXELFLOW :: an intergalactic discourse
    = stylesheet_link_tag 'css/reset.css'
    = stylesheet_link_tag 'css/text.css'
    = stylesheet_link_tag 'css/960.css'
    = stylesheet_link_tag 'css/fonts.css'
    = stylesheet_link_tag 'application.css'
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    .container_12
      .grid_12
        = render 'layouts/header'
      .clear
      .grid_12
        - if notice
          #notice= notice
        ~ yield
      /.grid_3
      /= render 'layouts/fork_me'
      /= render 'layouts/about'
      /= render 'layouts/twitter'
      /= render 'layouts/links'
      .clear
    = render 'layouts/analytics'

app/views/portfolio/index.html.haml
- @projects.each_with_index do |project, index|
  %div{class: index.even? ? "grid_6 alpha" : "grid_6 omega"}
    .project{style: "background-image: url('#{image_path(project[:image])}')"}
      %h1.title
        = link_to project[:url], target: "_blank" do
          = project[:name]